AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcCidr:
    Type: String
    Default: '10.0.0.0/16'

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      InstanceTenancy: default

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref VpcCidr/24
      Tags:
        - Key: user
          Value: Dra477
        - Key: stelligent-u-lesson
          Value: four
        - Key: stelligent-u-lab
          Value: foursevenseven

Outputs:
  VpcId:
    Value: !Ref Vpc
  SubnetId:
    Value: !Ref Subnet
