AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Parameters:
  BucketName:
    Description: Name of Bucket
    Type: String
    Default: enter-name-of-bucket-here

Conditions:
  PreferredRegion: !Equals
    - !Ref "AWS::Region"
    - "us-east-1"
  NotPreferredRegion: !Not
    - !Equals
      - !Ref "AWS::Region"
      - "us-east-1"

Resources:
  S3BucketPreferred:
    Type: AWS::S3::Bucket
    Condition: PreferredRegion
    Properties:
      BucketName: !Sub "${AWS::AccountId}-${BucketName}"
      AccessControl: PublicRead

  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: NotPreferredRegion
    Properties:
      BucketName: !Sub "${AWS::Region}-${BucketName}"
      AccessControl: PublicRead