AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template by Robert Webb

### Parameters ###

Parameters:
  UserName:
    Type: String
    Description: The name for the IAM User

### Resources ###

Resources:
  S3ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
            Resource: "arn:aws:s3:::*"
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: "arn:aws:s3:::*/*"
      Description: Allows read access to all S3 Buckets
      ManagedPolicyName: S3ReadOnlyPolicy

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName

  IAMPolicyAttachment:
    Type: AWS::IAM::Policy
    Properties:
      PolicyArn: !Ref S3ReadOnlyPolicy
      Users:
        - !Ref UserName

### Outputs ###

Outputs:
  UserName:
    Description: The name of the IAM User
    Value: !Ref UserName
