AWSTemplateFomatVersion: 2010-09-09


Paramaters:
  OneTimePassword:
    Type: String
    Description: Password used on first login

Resources:

  DefaultUser:
    Type: AWS::IAM::User
    Properties:
      UserName: DefaultUser
      LoginProfile:
        Password:
          Ref: OneTimePassword
        PasswordResetRequired: true
  DefaultPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DefaultPolicy
      Description: IAM Managed Policy For Testing
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -  Effect: Allow
             Action:
              - s3:GetBucketPolicy
              - s3:GetBucketPolicyStatus
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketWebsite
              - s3:GetBucketPublicAccessBlock
              - s3:GetBucketTagging
              - s3:GetBucketLoggging
              - s3:GetLifeCycleConfiguration
              - s3:GetAccelerateConfiguration
              - s3:GetAccessPoint
             Resource:
              - arn:aws:s3:::*