AWSTemplateFormatVersion: "2010-09-09"

Description: A sample template

Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-bucket-477
  
  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          StringEquals:
            s3:x-amz-acl: 'public-read'

      Policy:
        Statement:
          StringLike:
            s3:prefix: [private.txt]
            s3:x-amz-acl: 'authenticated-read'

  MyIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: stellu477
      PolicyDocument:
        Version: '2012-10-17'
        Statement: