AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-bucket-
      VersioningConfiguration:
        Status: Enabled

  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - sid: PublicReadAccess
          Effect: Allow
          Principal: '*'
          Action: 'S3:GetObject'
          Resource: 'arn:aws:s3:::my-bucket-477/*'
  
  MyObject:
    Type: 'AWS::S3::Object'
    Properties:
      Bucket: !Ref MyBucket
      Key: private.txt
      S3AccessControl: AuthenticatedRead
